import { createAsyncThunk } from '@reduxjs/toolkit';

import httpRequest from 'services/httpRequest';
import { FETCH_EMPLOYERS } from './apiUrls';

import { IResponseEmployers, IFetchEmployerArgs } from './interface';

const mockData = {
  data: [
    {
      PolicyId: 'c7a768c3-1b61-41e1-ab03-460ec122c50f',
      CompanyId: 323,
      CompanyName: 'ZURI HOTEL MANAJEMEN, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'Avrist Assurance, PT',
      InsuranceBroker: 'PAIB Indonesia, PT',
      PolicyNumber: '0000092910',
      IsActive: true,
      BrokerCompanyId: 185,
      InsurerCompanyId: 8,
      TotalActiveMember: 88,
      CountryName: 'Indonesia',
      InsuranceCurrency: null,
      TotalActivePremium: 38194939,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'c7a768c3-1b61-41e1-ab03-460ec122c50f',
      CompanyId: 323,
      CompanyName: 'ZURI HOTEL MANAJEMEN, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'Avrist Assurance, PT',
      InsuranceBroker: 'PAIB Indonesia, PT',
      PolicyNumber: '0000092910',
      IsActive: true,
      BrokerCompanyId: 185,
      InsurerCompanyId: 8,
      TotalActiveMember: 1,
      CountryName: 'Indonesia',
      InsuranceCurrency: 'ALL',
      TotalActivePremium: 7598564,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'c7a768c3-1b61-41e1-ab03-460ec122c50f',
      CompanyId: 323,
      CompanyName: 'ZURI HOTEL MANAJEMEN, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'Avrist Assurance, PT',
      InsuranceBroker: 'PAIB Indonesia, PT',
      PolicyNumber: '0000092910',
      IsActive: true,
      BrokerCompanyId: 185,
      InsurerCompanyId: 8,
      TotalActiveMember: 31,
      CountryName: 'Indonesia',
      InsuranceCurrency: 'IDR',
      TotalActivePremium: 1622703,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: '930bc688-5376-4293-b1c3-fa4198b9f82e',
      CompanyId: 312,
      CompanyName: 'YAYASAN MENARA BHAKTI QQ UNIVERSITAS MERCU BUANA',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'Asuransi Jiwa Central Asia Raya, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: '010075366',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 16,
      TotalActiveMember: 1729,
      CountryName: 'Indonesia',
      InsuranceCurrency: null,
      TotalActivePremium: 42441972,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'bbe52ccb-8269-4604-a9b0-1916b74b19f3',
      CompanyId: 317,
      CompanyName: 'WONDERFUL INDAH JAYA, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'BNI Life Insurance, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: '1930/PK-KES/0616',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 13,
      TotalActiveMember: 4,
      CountryName: 'Indonesia',
      InsuranceCurrency: 'IDR',
      TotalActivePremium: 5051600,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'bbe52ccb-8269-4604-a9b0-1916b74b19f3',
      CompanyId: 317,
      CompanyName: 'WONDERFUL INDAH JAYA, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'BNI Life Insurance, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: '1930/PK-KES/0616',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 13,
      TotalActiveMember: 32,
      CountryName: 'Indonesia',
      InsuranceCurrency: null,
      TotalActivePremium: 15282000,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'c6a12778-db9f-4866-8759-0b25f8caf6bb',
      CompanyId: 284,
      CompanyName: 'Wisata Triloka Buana - Le Meridien Hotel, PT',
      RegistrationNumber: '12345678910',
      NPWPNumber: '028087153023000',
      Insurer: 'Asuransi Reliance Indonesia, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: '01181201100190700',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 64,
      TotalActiveMember: 23,
      CountryName: 'Indonesia',
      InsuranceCurrency: 'USD',
      TotalActivePremium: 2125700,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'c6a12778-db9f-4866-8759-0b25f8caf6bb',
      CompanyId: 284,
      CompanyName: 'Wisata Triloka Buana - Le Meridien Hotel, PT',
      RegistrationNumber: '12345678910',
      NPWPNumber: '028087153023000',
      Insurer: 'Asuransi Reliance Indonesia, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: '01181201100190700',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 64,
      TotalActiveMember: 68,
      CountryName: 'Indonesia',
      InsuranceCurrency: null,
      TotalActivePremium: 16290400,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: '7cbf81ea-7923-49da-9dbd-611738ee33a2',
      CompanyId: 342,
      CompanyName: 'Weefer Indonesia, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'BNI Life Insurance, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: '5645/PK-SME/0821',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 13,
      TotalActiveMember: 45,
      CountryName: 'Indonesia',
      InsuranceCurrency: null,
      TotalActivePremium: 6011500,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
    {
      PolicyId: 'e2e82a87-1a3e-48af-973b-e3526ff1b357',
      CompanyId: 346,
      CompanyName: 'Twibbonize Teknologi Indonesia, PT',
      RegistrationNumber: null,
      NPWPNumber: null,
      Insurer: 'Asuransi Multi Artha Guna Tbk, PT',
      InsuranceBroker: 'Global Insurance Broker, PT',
      PolicyNumber: 'JKT.GHS.949.001',
      IsActive: true,
      BrokerCompanyId: 134,
      InsurerCompanyId: 60,
      TotalActiveMember: 13,
      CountryName: 'Indonesia',
      InsuranceCurrency: null,
      TotalActivePremium: 11605248,
      TotalPremiumRenewal: 0,
      Currency: null,
    },
  ],
  totalCount: 70,
};

export const fetchEmployers = createAsyncThunk<any, IFetchEmployerArgs, { rejectValue: string }>(
  'employers/fetch',
  async (payload, thunkAPI) => {
    try {
      // let { data } = await httpRequest.get(FETCH_EMPLOYERS, { params: payload });
      const data = mockData.data;

      return data;
    } catch (err: any) {
      return thunkAPI.rejectWithValue(err);
    }
  },
);
